#!/bin/bash

install_dir="$(realpath "$(dirname "$(realpath "$0")")/..")"
GIXPP="$install_dir/bin/gixpp"
if test ! -f "$GIXPP"; then
   GIXPPBIN="$install_dir/gixpp/gixpp"  # use (guessed) build directory
   test -f "$GIXPPBIN" && GIXPP="$GIXPPBIN"
fi

if test "x$2" == "x"; then
   case "$1" in
     -V | --version)
       printf "GixSQL wrapper script to "  # further output from gixpp inline
       ;;
     "")
       echo "Usage: gixsql input-file output-file [options]..."
       echo "Try 'gixsql --help' for more information."
       exit 1
       ;;
     -h | --h*)
       echo "GixSQL wrapper script to gixpp"
       echo ""
       echo "Usage: gixsql input-file output-file [options]..."
       echo ""
       echo "Help for gixpp, which documents additional options to use, follows (see \"ESQL:\")."
       echo ""
       ;;
   esac
   "$GIXPP" -e "$1"
else
   input="$1"; shift
   output="$1"; shift
   "$GIXPP" -e -I "$install_dir/share/gixsql/copy" -i "$input" -o "$output" $*
fi
