name: gixsql-windows-test

on:
  workflow_dispatch

env:
  WORKSPACE: ${{ github.workspace }}
  INSTALL_DIR: ${{ github.workspace }}\gixsql-install
  GIXSQL_BRANCH: main

permissions:
  contents: read

jobs:
  gixsql-windows-x64-msvc-mingw-test:
    name: gixsql-windows-test-x64-msvc-mingw
    env:
        PKG_NAME: gixsql-installer-windows-x64-msvc-mingw-1.0.19dev1-826
        
    runs-on: windows-latest
    
    steps:
    
    - uses: ikalnytskyi/action-setup-postgres@v3
      with:
        username: ci
        password: sw0rdfish
        database: test
        port: 34837
      id: postgres
  
      
    - uses: actions/checkout@v3
      with:
          repository: 'mridoni/gixsql'
          submodules: true
          ref: ${{ env.GIXSQL_BRANCH }}
          
    - name: Build
      shell: cmd
      working-directory: ${{ github.workspace }}
      env:
          QTDIR: ${{env.Qt5_Dir}}
          QtMsBuild: ${{ github.workspace }}\QtMsBuild
          QtToolsPath: ${{env.Qt5_Dir}}\bin
          LIBPATH: ${{env.Qt5_Dir}}\lib
          PATH: ${{ env.PATH}};c:\tools
      run: |
        echo "VCPKG_ROOT         : ${{env.VCPKG_ROOT}}"
        echo "HOST_PLATFORM      : ${{env.HOST_PLATFORM}}"
        echo "BUILD_CONFIGURATION: ${{env.BUILD_CONFIGURATION}}"
        echo "SOLUTION_FILE_PATH : ${{env.SOLUTION_FILE_PATH}}"
        echo "QTDIR              : ${{env.QTDIR}}"
        echo "JOB                : ${{ github.job }}"
        "%EXE_7Z%" x -y ${{ github.workspace }}\build-tools\QtMsBuild.zip  
        call ${{ github.workspace }}\prepbuild.cmd /E
        %VCPKG_ROOT%\vcpkg integrate install
        msbuild /p:Platform=${{env.HOST_PLATFORM}} /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /p:IncludePath="${{env.Qt5_Dir}}/include;${{env.Qt5_Dir}}/include/QtCore;${{env.Qt5_Dir}}/include/QtWidgets;${{env.Qt5_Dir}}/include/QtXml;${{env.Qt5_Dir}}/include/QtXmlPatterns;${{env.Qt5_Dir}}/include/QtNetwork;${{env.Qt5_Dir}}/include/QtUiTools;${{env.Qt5_Dir}}/include/QtGui;${{ '$(IncludePath)' }}" /p:LibPath="${{env.Qt5_Dir}}/lib;${{ '$(LibPath)' }}" /p:AdditionalDependencies="${{env.QTDIR}}\lib\Qt5Widgets.lib" /p:AdditionalDependencies="${{env.QTDIR}}\lib\Qt5Gui.lib" /p:AdditionalDependencies="${{env.QTDIR}}\lib\Qt5Core.lib ${{env.QTDIR}}\lib\qtmain.lib"
          

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2