name: gixsql-ubuntu-packages

on:
  workflow_dispatch
  
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

env:
  GIXSQLMAJ: 1
  GIXSQLMIN: 0
  GIXSQLREL: 19
  GIX_REVISION: 900

permissions:
  contents: read

jobs:
  ubuntu-20-04-x64:
    name: ubuntu-20.04-x64
    env:
      BUILD_CONFIGURATION: Release
      BUILD_PLATFORM: x64      
      HOST_PLATFORM: x64    
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v3
      with:
          repository: 'mridoni/gix'
          ref: new-debugger
    
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
          packages: build-essential libmysqlclient-dev libpq-dev unixodbc-dev flex libspdlog-dev libfmt-dev
          version: 1.0

    - name: Build source package
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        wget http://ftp.debian.org/debian/pool/main/b/bison/bison_3.7.5+dfsg-1_amd64.deb
        sudo dpkg -i bison_3.7.5+dfsg-1_amd64.deb      
        chmod 755 prepdist.sh && ./prepdist.sh
        autoreconf --install --force
        ./configure
        make distcheck
    
    - name: Build package
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        WORKSPACE: ${{ github.workspace }}
        HOST_PLATFORM: ${{ env.HOST_PLATFORM }}
        DIST: ubuntu-20.04-lts
        GIXSQLMAJ: ${{ env.GIXSQLMAJ }}
        GIXSQLMIN: ${{ env.GIXSQLMIN }}
        GIXSQLREL: ${{ env.GIXSQLREL }}
        GIX_REVISION: ${{ env.GIX_REVISION }}
      run: |
        chmod 755 ${{ github.workspace }}/deploy/installers/linux/mkdeb.sh && ${{ github.workspace }}/deploy/installers/linux/mkdeb.sh
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      env:
        WORKSPACE: ${{ github.workspace }}
        HOST_PLATFORM: ${{ env.HOST_PLATFORM }}
        DIST: ubuntu-20.04-lts
      with:
        name: gixsql-${{ env.DIST }}-${{ env.HOST_PLATFORM }}-${{ env.GIXSQLMAJ}}.${{ env.GIXSQLMIN}}.${{ env.GIXSQLREL}}-${{ env.GIX_REVISION}}
        path: |
          gixsql-${{ env.DIST }}-${{ env.HOST_PLATFORM }}-${{ env.GIXSQLMAJ}}.${{ env.GIXSQLMIN}}.${{ env.GIXSQLREL}}-${{ env.GIX_REVISION}}.deb


  ubuntu-22-04-x64:
    name: ubuntu-22.04-x64
    env:
      BUILD_CONFIGURATION: Release
      BUILD_PLATFORM: x64      
      HOST_PLATFORM: x64    
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v3
      with:
          repository: 'mridoni/gix'
          ref: new-debugger
    
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
          packages: build-essential libmysqlclient-dev libpq-dev unixodbc-dev flex libspdlog-dev libfmt-dev
          version: 1.0

    - name: Build package
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        WORKSPACE: ${{ github.workspace }}
        HOST_PLATFORM: ${{ env.HOST_PLATFORM }}
        DIST: ubuntu-20.04-lts
        GIXSQLMAJ: ${{ env.GIXSQLMAJ }}
        GIXSQLMIN: ${{ env.GIXSQLMIN }}
        GIXSQLREL: ${{ env.GIXSQLREL }}
        GIX_REVISION: ${{ env.GIX_REVISION }}
      run: |
        chmod 755 ${{ github.workspace }}/deploy/installers/linux/mkdeb.sh && ${{ github.workspace }}/deploy/installers/linux/mkdeb.sh
    
    - name: Build package
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        WORKSPACE: ${{ github.workspace }}
        HOST_PLATFORM: ${{ env.HOST_PLATFORM }}
        DIST: ubuntu-22.04-lts
        GIXSQLMAJ: ${{ env.GIXSQLMAJ }}
        GIXSQLMIN: ${{ env.GIXSQLMIN }}
        GIXSQLREL: ${{ env.GIXSQLREL }}
        GIX_REVISION: ${{ env.GIX_REVISION }}
      run: |
        chmod 755 ${{ github.workspace }}/deploy/installers/linux/mkdeb.sh && ${{ github.workspace }}/deploy/installers/linux/mkdeb.sh
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      env:
        WORKSPACE: ${{ github.workspace }}
        HOST_PLATFORM: ${{ env.HOST_PLATFORM }}
        DIST: ubuntu-22.04-lts
        GIXSQLMAJ: ${{ env.GIXSQLMAJ }}
        GIXSQLMIN: ${{ env.GIXSQLMIN }}
        GIXSQLREL: ${{ env.GIXSQLREL }}
        GIX_REVISION: ${{ env.GIX_REVISION }}      
      with:
        name: gixsql-${{ env.DIST }}-${{ env.HOST_PLATFORM }}-${{ env.GIXSQLMAJ}}.${{ env.GIXSQLMIN}}.${{ env.GIXSQLREL}}-${{ env.GIX_REVISION}}
        path: |
          gixsql-${{ env.DIST }}-${{ env.HOST_PLATFORM }}-${{ env.GIXSQLMAJ}}.${{ env.GIXSQLMIN}}.${{ env.GIXSQLREL}}-${{ env.GIX_REVISION}}.deb

