name: gixsql-ubuntu-packages

on:
  workflow_dispatch
  
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

env:
  GIXSQLMAJ: 1
  GIXSQLMIN: 0
  GIXSQLREL: 20a
  GIX_REVISION: ${{ github.run_attempt }}
  GIXSQL_BRANCH: ${{ github.ref_name }}
  INSTALL_PREFIX: usr
  HOST_PLATFORM: x64   
  
permissions:
  contents: read

jobs:
  ubuntu-20-04-x64:
    name: ubuntu-20.04-x64
    env:
      DIST: ubuntu-20.04-lts
      
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v3
      with:
          repository: 'mridoni/gixsql'
          ref: ${{ env.GIXSQL_BRANCH }}
    
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
          packages: build-essential libmysqlclient-dev libpq-dev unixodbc-dev flex libspdlog-dev libfmt-dev
          version: 1.0

    - name: Build GixSQL
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        wget http://ftp.debian.org/debian/pool/main/b/bison/bison_3.7.5+dfsg-1_amd64.deb
        sudo dpkg -i bison_3.7.5+dfsg-1_amd64.deb      
        chmod 755 prepdist.sh && ./prepdist.sh
        autoreconf --install --force
        ./configure --prefix=${{ github.workspace }}/pkg/${{ env.INSTALL_PREFIX }}
        make -j$(nproc) && make install-strip
    
    - name: Build .deb package
      env:
          WORKSPACE: ${{ github.workspace }}    
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        chmod 755 $WORKSPACE/deploy/installers/linux/mkdeb-gixsql.sh && $WORKSPACE/deploy/installers/linux/mkdeb-gixsql.sh
        ls -l
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: gixsql-${{ env.DIST }}-${{ env.HOST_PLATFORM }}-${{ env.GIXSQLMAJ}}.${{ env.GIXSQLMIN}}.${{ env.GIXSQLREL}}-${{ env.GIX_REVISION}}
        path: |
          gixsql-${{ env.DIST }}-${{ env.HOST_PLATFORM }}-${{ env.GIXSQLMAJ}}.${{ env.GIXSQLMIN}}.${{ env.GIXSQLREL}}-${{ env.GIX_REVISION}}.deb


  ubuntu-22-04-x64:
    name: ubuntu-22.04-x64
    env:
      DIST: ubuntu-22.04-lts
      
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v3
      with:
          repository: 'mridoni/gixsql'
          ref: ${{ env.GIXSQL_BRANCH }}
    
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
          packages: build-essential libmysqlclient-dev libpq-dev unixodbc-dev flex libspdlog-dev libfmt-dev
          version: 1.0

    - name: Build GixSQL
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        chmod 755 ./prepbuild.sh && ./prepbuild.sh /E
        chmod 755 ./prepdist.sh && ./prepdist.sh
        autoreconf --install --force
        ./configure --prefix=${{ github.workspace }}/pkg/${{ env.INSTALL_PREFIX }}
        make -j$(nproc) && make install-strip
    
    - name: Build .deb package
      env:
          WORKSPACE: ${{ github.workspace }}      
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        chmod 755 $WORKSPACE/deploy/installers/linux/mkdeb-gixsql.sh && $WORKSPACE/deploy/installers/linux/mkdeb-gixsql.sh
        ls -l

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: gixsql-${{ env.DIST }}-${{ env.HOST_PLATFORM }}-${{ env.GIXSQLMAJ}}.${{ env.GIXSQLMIN}}.${{ env.GIXSQLREL}}-${{ env.GIX_REVISION}}
        path: |
          gixsql-${{ env.DIST }}-${{ env.HOST_PLATFORM }}-${{ env.GIXSQLMAJ}}.${{ env.GIXSQLMIN}}.${{ env.GIXSQLREL}}-${{ env.GIX_REVISION}}.deb

